<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.545">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Irsyad Atmaja Nasution">
<meta name="dcterms.date" content="2024-01-20">

<title>Pengaruh Ekspor Minyak Mentah Indonesia Terhadap GDP Indonesia Tahun 2013 - 2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Ekspor Minyak Mentah Indonesia Terhadap GDP Indonesia Tahun 2013 - 2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Irsyad Atmaja Nasution </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 20, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><img src="poltekapp.jpg" class="img-fluid" width="320"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar Belakang</h3>
<p>Perdagangan Internasional merupakan salah satu aspek penting dalam perekonomian setiap negara di dunia, sehingga mengacu pada pertumbuhan ekonomi suatu negara. Gross Domestic Pruduct (GDP) atau Produk Domestik Bruto (PDB) merupakan indikator makroekonomi yang sampai saat ini yang masih digunakan untuk mengukur kinerja perekonomian di suatu negara. Interaksi ekonomi antar negara menjadi faktor utama dalam pertumbuhan ekonomi suatu negara.</p>
<p>Alkadri (2000) dan Tumovsky (2000), mendefinisikan pertumbuhan ekonomi sebagai besarnya persentase perubahan pada indikator Produk Domestik Bruto (PDB). Ekspor merupakan komponen utama untuk pertumbuhan ekonomi di suatu negara, dimana suatu negara dapat memperoleh keuntungan dan pendapatan nasional. Transaksi internasional terjadi ketika suatu negara memiliki kelebihan produksi dalam negeri kemudian negara tersebut akan melakukan ekspor ke negara lain.</p>
<p>Menurut Bank Indonesia (BI), neraca pembayaran merupakan catatan sebagai catatan transaksi ekonomi antara penduduk Indonesia dengan non-residen dalam suaru periode tertentu. Surplus neraca pembayaran terjadi jika suatu negara memiliki kelebihan nilai ekspor dan investasi dibandingkan kewajiban yang dibayarkan negara lain. Dimana kondisi neraca pembayaran defisit terjadi saat impor lebih besar dibandingkan ekspor, neraca pembayaran surplus berdampak pada pertumbuhan ekonomi suatu negara.</p>
<p>Minyak mentah berkontribusi cukup besar terhadap total nilai ekspor migas di Indonesia, perkembangan ekspor impor minyak mentah di Indonesia setiap tahunnya mengalami fluktuasi, adapun beberapa faktor ekonomi juga dapat mempengaruhi besarnya nilai ekspor minyak bumi mentah. Faktor ini antara lain, tingkat kurs, jumlah PDB, dan tingkat fluktuasi dari kurs karena mempengaruhi jumlah permintaan atau kuantitas minyak mentah yang diminta oleh importir, dan juga tingkat inflasi. Tingkat inflasi karena indikasi kenaikan harga barang, jika laju inflasi semakin tinggi akan berdampak pada penurunan nilai ekspor. Industri minyak dan gas diputuskan pemerintah sebagai industri yang tepat, menurut EIA (2011) negara Indonesia merupakan negara eksportir gas alam terbesar ke-8. Penelitian ini dimaksudkan apakah nilai ekspor minyak mentah Indonesia berpengaruh terhadap GDP Indonesia.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang Lingkup</h3>
<p>Penelitian ini meneliti dan menganalisa pengaruh ekspor minyak mentah Indonesia terhadap GDP Indonesia pada periode 10 tahun terakhir yaitu pada tahun 2013 sampai dengan tahun 2022. Ruang lingkup penelitian ini adalah pada variabel - variabel yang berkaitan dengan judul penelitian yaitu ekspor dan GDP.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan Masalah</h3>
<ol type="1">
<li>Apakah nilai ekspor minyak mentah Indonesia berpengaruh pada GDP Indonesia?</li>
<li>Seberapa besar pengaruh nilai ekspor minyak mentah di Indonesia terhadap GDP Indonesia tahun 2013 - 2022?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan Manfaat Penelitian</h3>
<p><strong>Tujuan</strong> <strong>Penelitian</strong></p>
<p>Penelitian ini bertujuan untuk melihat bagaimana pengaruh nilai ekspor komoditas minyak mentah di Indonesia terhadap GDP Indonesia dalam periode 10 tahun terakhir serta mengevaluasi bagaimana keunggulan nilai ekspor minyak mentah Indonesia terhadap GDP Indonesia periode tahun 2013 - 2022.</p>
<p><strong>Manfaat Penelitian</strong></p>
<ol type="1">
<li><p><strong>Meningkatkan pemahaman tentang hubungan antara ekspor minyak mentah dan GDP Indonesia.</strong> Penelitian ini dapat memberikan gambaran yang lebih jelas tentang bagaimana ekspor minyak mentah mempengaruhi GDP Indonesia, baik secara langsung maupun tidak langsung.</p></li>
<li><p><strong>Meningkatkan pemahaman tentang ekonomi makro.</strong> Penelitian ini dapat memberikan gambaran yang lebih jelas tentang bagaimana faktor-faktor makroekonomi, seperti ekspor minyak mentah, dapat mempengaruhi pertumbuhan ekonomi.</p></li>
<li><p><strong>Meningkatkan pertumbuhan ekonomi yang berkelanjutan.</strong> Peningkatan ekspor minyak mentah dapat membantu Indonesia untuk mencapai pertumbuhan ekonomi yang berkelanjutan.</p></li>
</ol>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan dalam penelitian ini, antara lain:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi Pustaka</h2>
<p><strong>Ekspor</strong> Ekspor merupakan salah satu unsur yang dapat meningkatkan pertumbuhan ekonomi. Sistematis ekspor merupakan penjualan barang ke luar negeri dengan menggunakan sistem pembayaran, kualitas, kuantitas dan syarat penjualan lain yang telah disetujui oleh pihak eksportir dan importir berupa negosiasi atau membuat kontrak dari kedua pihak yaitu importir dan eksportir. Proses ekspor pada umumnya merupakan tindakan untuk mengeluarkan barang/komoditas dari dalam negeri untuk memasukannya ke negara lain. Ekspor barang secara besar umumnya membutuhkan campur tangan bea cukai negara pengirim maupun penerima.</p>
<p>Menurut (Amir, 2013), Ekspor adalah upaya melakukan penjualan komoditas yang kita miliki kepada bangsa lain atau Negara asing, dengan mengharapkan pembayaran dalam valuta asing, serta melakukan komoditi dengan memakai bahasa asing. Menurut (Marolop, 2011), Ekspor adalah pengeluaran barang dari daerah pabeanan indonesia untuk dikirim ke luar negeri dengan mengikuti ketentuan yang berlaku terutama mengenai peraturan kepabeanan.</p>
<p>Aktifitas ekspor minyak mentah ini membantu pemerintah memperoleh pendapatan dan meningkatkan pertumbuhan ekonomi suatu negara. Semakin banyak ekspor minyak mentah maka devisa negara tersebut bertambah dan nilai tukar uang luar negeri pun tidak stabil, maka dari itu ekspor menyebabkan suatu negara mendapat mata uang asing dan sebaliknya impor harus dibayar dengan mata uang asing. Transaksi tersebut akan di catat oleh Bank Sentral dan nilainya ditunjukan dalam neraca pembayaran. Dapat di artikan bahwa apabila suatu negara ekspornya lebih besar di banding impornya maka Negara tersebut akan terjadi peningkatan pertumbuhan ekonomi.</p>
<p><strong>Minyak Mentah</strong> Minyak mentah Indonesia adalah salah satu sumber daya alam utama negara ini, Indonesia memiliki potensi yang besar untuk menjadi produsen minyak mentah dunia. Hal ini karena Indonesia memiliki cadangan minyak mentah yang cukup besar, yaitu sekitar 3,5 miliar barel memiliki sejumlah ladang minyak yang tersebar di berbagai wilayah, terutama di Pulau Sumatera, Kalimantan, dan Papua. Pengaruh ekspor minyak mentah terhadap GDP (Gross Domestic Product) Indonesia dari tahun 2013 hingga 2022 merupakan topik yang kompleks dan melibatkan berbagai faktor ekonomi.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode Penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Nilai Ekspor (US$)</th>
<th>GDP Indonesia (US$)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2013</td>
<td>10204000000</td>
<td>912524136718</td>
</tr>
<tr class="even">
<td>2014</td>
<td>9215000000</td>
<td>890814755533</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>6479000000</td>
<td>860854232686</td>
</tr>
<tr class="even">
<td>2016</td>
<td>5196000000</td>
<td>931877364037</td>
</tr>
<tr class="odd">
<td>2017</td>
<td>5354000000</td>
<td>1015618744159</td>
</tr>
<tr class="even">
<td>2018</td>
<td>5151000000</td>
<td>1042271532988</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>1726000000</td>
<td>1119099871350</td>
</tr>
<tr class="even">
<td>2020</td>
<td>1396000000</td>
<td>1059054842698</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>2795000000</td>
<td>1186505455736</td>
</tr>
<tr class="even">
<td>2022</td>
<td>1615000000</td>
<td>1319100220407</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data nilai ekspor Minyak Mentah tahun 2013 - 2022 dari Badan Pusat Statistika (BPS) dan GDP Indonesia menggunakan data dari Worldbank.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>Data_Irsyad<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/Data Irsyad/UAS/Data Irsyad.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Data_Irsyad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Tahun NilaiEkspor           GDP
  &lt;dbl&gt;       &lt;dbl&gt;         &lt;dbl&gt;
1  2013 10204000000  912524136718
2  2014  9215000000  890814755533
3  2015  6479000000  860854232686
4  2016  5196000000  931877364037
5  2017  5354000000 1015618744159
6  2018  5151000000 1042271532988</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>Data_Irsyad,<span class="fu">aes</span>(<span class="at">x=</span>NilaiEkspor,<span class="at">y=</span>GDP)) <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"blue"</span>,<span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span> <span class="co"># setiap nambah command, selalu kasih tanda +</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"tabel 1. Hubungan Antara Nilai Ekspor Minyak Mentah terhadap GDP Indonesia"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Nilai Ekspor Minyak Mentah"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"GDP Indonesia"</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: Worldbank , BPS"</span>) <span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 14 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode Analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini bermaksud mencari hubungan antara nilai ekspor minyak mentah dan GDP Indonesia. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah nilai ekspor minyak mentah dan <span class="math inline">\(x_t\)</span> adalah GDP Indonesia.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Dikarenakan penelitian ini menggunakan OLS, pembahasan disini merupakan menghubungkan Nilai Ekspor Minyak Mentah (NilaiEkspor) dan GDP Indonesia (GDP) pada tahun 2013 - 2022, yang dimana dari kedua data tersebut disatukan untuk regresi, berikut adalah tampilannnya:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#import dataset</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>Data_Irsyad<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/Data Irsyad/UAS/Data Irsyad.xlsx"</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Data_Irsyad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Tahun NilaiEkspor           GDP
  &lt;dbl&gt;       &lt;dbl&gt;         &lt;dbl&gt;
1  2013 10204000000  912524136718
2  2014  9215000000  890814755533
3  2015  6479000000  860854232686
4  2016  5196000000  931877364037
5  2017  5354000000 1015618744159
6  2018  5151000000 1042271532988</code></pre>
</div>
</div>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/Data Irsyad/UAS/Data Irsyad.xlsx"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data =</span> dat,GDP<span class="sc">~</span>NilaiEkspor)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = GDP ~ NilaiEkspor, data = dat)

Residuals:
       Min         1Q     Median         3Q        Max 
-1.157e+11 -7.646e+10  6.154e+09  5.846e+10  1.647e+11 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.213e+12  5.821e+10   20.84 2.94e-08 ***
NilaiEkspor -3.656e+01  1.016e+01   -3.60  0.00698 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.482e+10 on 8 degrees of freedom
  (14 observations deleted due to missingness)
Multiple R-squared:  0.6184,    Adjusted R-squared:  0.5707 
F-statistic: 12.96 on 1 and 8 DF,  p-value: 0.00698</code></pre>
</div>
</div>
<p>Dapat dilihat dari regresinya dapat dimasukkan ke dalam model adalah menjadi sebgai berikut :</p>
<p><span class="math display">\[
y_{t}= 1.213e+12 + -3.656e+07 +\mu_t
\]</span></p>
<p>Dapat dijelaskan bahwa :</p>
<ol type="1">
<li>Konstanta ???? adalah sebesar 1.213e+12 menunjukan konstanta GDP (Y).</li>
<li>Koefisien regresi nilai ekspor (X) minyak mentah menunjukan sebesar -3.656e+07, menyatakan adanya hubungan yang negatif sehingga menunjukan hubungan yang tidak searah, dapat diartikan bahwa nilai ekspor minyak mentah turun dan GDP menunjukan nilai naik.</li>
</ol>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Berdasarkan hasil analisis regresi tersebut, dapat kita simpulkan bahwa terdapat hubungan negatif yang signifikan secara statistik antara GDP dan Nilai Ekspor, dimana ketika Nilai Ekspor meningkat, GDP cenderung menurun. R-squared menunjukan nilai 0.6184 artinya 61.84% variasi dalam GDP dapat dijelaskan oleh variasi dalam Nilai Ekspor, nilai ini cukup tinggi, tetapi masih menyisakan ruang untuk faktor lain yang mempengaruhi GDP.</p>
<p>Koefisien regresi dari penelitian ini sebesar -3.656e+01 untuk variabel independen (NilaiEkspor) menunjukkan bahwa setiap kenaikan Nilai Ekspor sebesar 1 unit dikaitkan dengan penurunan GDP sebesar 36.56 unit. Sementara itu hasil dari p-value dari regresi tersebut menunjukan P-value 0.00698 (kurang dari 0.05) menunjukkan bahwa hubungan antara GDP dan Nilai Ekspor tidak terjadi secara kebetulan. Hubungan antara kedua variabel yang disebut hubungan negatif signifikan secara statistik.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>World Bank. (2023, January 24). GDP (current US$). Indonesia. Retrieved from The World Bank: https://databank.worldbank.org/reports.aspx?source=2&amp;series=NY.GDP.MKTP.CD&amp;country=IDN</p>
<p>Badan Pusat Statistik Indonesia. (8 September 2014). Nilai Ekspor dan Impor Migas (juta US$) 1996-2022. Diakses pada 19 Januari 2024, dari https://www.bps.go.id/id/statistics-table/1/MTAwNCMx/nilai-ekspor-dan-impor-migas--juta-us---1996-2022.html</p>
<p>M. Helmi Firmansyah, I Gusti Bagus Indrajaya. (2021). PENGARUH EKSPOR MINYAK BUMI MENTAH DAN IMPOR PRODUK MINYAK BUMI OLAHAN TERHADAP PERTUMBUHAN EKONOMI INDONESIA, 2278. https://ojs.unud.ac.id/index.php/eep/article/download/75925/45179/</p>
<p>Fadila Azra, Murtala. (2021). PENGARUH EKSPOR HASIL MINYAK DAN IMPOR MINYAK BUMI TERHADAP PERTUMBUHAN EKONOMI DI INDONESIA, 23-25. https://ojs.unimal.ac.id/ekonomika/article/download/4506/2474</p>
<p>Rahma Nurjanah, Adi Bhakti. (Juni 2020). Analisis determinan ekspor minyak mentah Indonesia, 51-52. https://repository.unja.ac.id/17542/1/9219-Article%20Text-32968-1-10-20210312.pdf</p>
<p>Fahrizal Yazid, Aris Soelistyo, Hendra Kusuma. (Agustus 2020). ANALISIS PENAWARAN EKSPOR MINYAK BUMI MENTAH INDONESIA PADA PASAR GLOBAL TAHUN 2009-2018, 472. https://ejournal.umm.ac.id/index.php/jie/article/view/12757</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>